# Generated by Django 4.2.14 on 2024-07-26 10:19

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
    ]
