# Generated by Django 4.2.14 on 2024-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Airline Staff', 'airline staff'), ('Airport Staff', 'airport staff'), ('Passenger', 'passenger'), ('Security Personnel', 'security personnel'), ('IT Support', 'IT support')], default='Passenger', max_length=200),
        ),
    ]
